matrix:
    include:
      - language: node_js
        node_js:
          - 12
        install:
          - npm install
        script:
          - npm test
  
notifications:
    email:
        - matheusgoislimasilva@gmail.com 